using Microsoft.Extensions.DependencyInjection;
using Routya.Core.Abstractions;
using Routya.Generated;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Routya.SourceGen.Demo
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("🚀 Routya Source Generator Demo");
            Console.WriteLine("================================\n");

            // Setup DI container with generated registration
            var services = new ServiceCollection();
            
            // Register pipeline behavior
            services.AddTransient(typeof(IPipelineBehavior<,>), typeof(LoggingPipelineBehavior<,>));
            
            services.AddGeneratedRoutya();  // ⏭️ Generated by source generator!

            var provider = services.BuildServiceProvider();
            var routya = provider.GetRequiredService<IGeneratedRoutya>();

            // Test request/response
            Console.WriteLine("Testing Request/Response:");
            var getUserRequest = new GetUserRequest { UserId = 123 };
            var user = await routya.SendAsync(getUserRequest);
            Console.WriteLine($"✅ Got user: {user.Name} (ID: {user.Id})");
            
            // Test notification
            Console.WriteLine("\nTesting Notifications:");
            var notification = new UserCreatedNotification { UserId = 456, Email = "test@example.com" };
            await routya.PublishAsync(notification);
            Console.WriteLine("✅ Notification published successfully");

            // Test streaming
            Console.WriteLine("\nTesting Streaming (Big Data):");
            var streamRequest = new GetLargeDatasetRequest { TotalRecords = 500, ChunkSize = 100 };
            var stream = await routya.SendAsync(streamRequest);
            
            int totalReceived = 0;
            await foreach (var chunk in stream)
            {
                totalReceived += chunk.Count;
                Console.WriteLine($"  → Received chunk {chunk.ChunkNumber + 1}: {chunk.Count} records (Total: {totalReceived})");
            }
            Console.WriteLine($"✅ Streaming completed: {totalReceived} records received");

            Console.WriteLine("\n🎉 Source generator is working!");
        }
    }

    // Request/Response example
    public class GetUserRequest : IRequest<User>
    {
        public int UserId { get; set; }
    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    public class GetUserHandler : IAsyncRequestHandler<GetUserRequest, User>
    {
        public Task<User> HandleAsync(GetUserRequest request, CancellationToken cancellationToken)
        {
            Console.WriteLine($"  → GetUserHandler executed for UserId: {request.UserId}");
            return Task.FromResult(new User
            {
                Id = request.UserId,
                Name = $"User_{request.UserId}"
            });
        }
    }

    // Notification example
    public class UserCreatedNotification : INotification
    {
        public int UserId { get; set; }
        public string Email { get; set; } = "";
    }

    public class EmailNotificationHandler : INotificationHandler<UserCreatedNotification>
    {
        public Task Handle(UserCreatedNotification notification, CancellationToken cancellationToken = default)
        {
            Console.WriteLine($"  → EmailNotificationHandler: Sending email to {notification.Email}");
            return Task.CompletedTask;
        }
    }

    public class AuditLogHandler : INotificationHandler<UserCreatedNotification>
    {
        public Task Handle(UserCreatedNotification notification, CancellationToken cancellationToken = default)
        {
            Console.WriteLine($"  → AuditLogHandler: Logging user creation for ID {notification.UserId}");
            return Task.CompletedTask;
        }
    }
}

