using Routya.SourceGenerators.Models;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Routya.SourceGenerators.Emitters;

/// <summary>
/// Emits optimized, type-specific dispatcher code for maximum performance.
/// Generates direct dispatch methods that bypass runtime generic resolution.
/// </summary>
internal static class DispatcherEmitter
{
    public static string EmitGeneratedDispatcher(
        List<HandlerDescriptor> requestHandlers,
        Dictionary<string, List<HandlerDescriptor>> notificationHandlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Routya.Core.Abstractions;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace Routya.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// High-performance, compile-time optimized dispatcher.");
        sb.AppendLine("    /// Generated methods provide zero-overhead, type-specific dispatch.");
        sb.AppendLine("    /// </summary>");
        GeneratedTypeAttributes.AppendForType(sb, "    ");
        sb.AppendLine("    public sealed class GeneratedRoutya : IGeneratedRoutya");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedRoutya(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate type-specific SendAsync methods
        foreach (var handler in requestHandlers)
        {
            EmitRequestDispatchMethod(sb, handler);
        }

        // Generate type-specific PublishAsync methods
        foreach (var kvp in notificationHandlers)
        {
            EmitNotificationDispatchMethod(sb, kvp.Key, kvp.Value);
        }

        // Generate generic fallback methods
        EmitGenericFallbackMethods(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRequestDispatchMethod(StringBuilder sb, HandlerDescriptor handler)
    {
        // IRequestHandler exposes Handle and IAsyncRequestHandler exposes HandleAsync, so the two
        // cannot share a dispatch body. The generated interface likewise declares Send for a
        // synchronous handler and SendAsync for an asynchronous one.
        if (handler.IsStream)
        {
            EmitStreamDispatchMethod(sb, handler);
        }
        else if (handler.IsAsync)
        {
            EmitAsyncRequestDispatchMethod(sb, handler);
        }
        else
        {
            EmitSyncRequestDispatchMethod(sb, handler);
        }
    }

    private static void EmitStreamDispatchMethod(StringBuilder sb, HandlerDescriptor handler)
    {
        var requestTypeName = handler.RequestType.ToGeneratedName();
        var responseTypeName = handler.ResponseType!.ToGeneratedName();
        var behaviorType = $"IStreamPipelineBehavior<{requestTypeName}, {responseTypeName}>";

        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Optimized streaming dispatch for {requestTypeName}.");
        sb.AppendLine("        /// Items are produced lazily and nothing is buffered.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public System.Collections.Generic.IAsyncEnumerable<{responseTypeName}> CreateStream(");
        sb.AppendLine($"            {requestTypeName} request,");
        sb.AppendLine($"            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request == null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();
        sb.AppendLine($"            var resolvedBehaviors = _serviceProvider.GetServices<{behaviorType}>();");
        sb.AppendLine($"            var behaviors = resolvedBehaviors as {behaviorType}[] ?? resolvedBehaviors.ToArray();");
        sb.AppendLine($"            var handler = _serviceProvider.GetRequiredService<{handler.ConcreteType}>();");
        sb.AppendLine();
        sb.AppendLine("            if (behaviors.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                // No behaviors - straight to the handler");
        sb.AppendLine("                return handler.Handle(request, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            StreamHandlerDelegate<{responseTypeName}> next = (ct) => handler.Handle(request, ct);");
        sb.AppendLine();
        sb.AppendLine("            // Walked in reverse so behaviors execute in registration order");
        sb.AppendLine("            for (int i = behaviors.Length - 1; i >= 0; i--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var currentBehavior = behaviors[i];");
        sb.AppendLine("                var currentDelegate = next;");
        sb.AppendLine("                next = (ct) => currentBehavior.Handle(request, currentDelegate, ct);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return next(cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitAsyncRequestDispatchMethod(StringBuilder sb, HandlerDescriptor handler)
    {
        var requestTypeName = handler.RequestType.ToGeneratedName();
        var responseTypeName = handler.ResponseType!.ToGeneratedName();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Optimized dispatch for {requestTypeName}.");
        sb.AppendLine("        /// Zero dictionary lookups, direct handler resolution.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public async Task<{responseTypeName}> SendAsync(");
        sb.AppendLine($"            {requestTypeName} request,");
        sb.AppendLine($"            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request == null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();
        EmitBehaviorAndHandlerResolution(sb, handler, requestTypeName, responseTypeName);
        sb.AppendLine();
        sb.AppendLine("            if (behaviors.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                // No behaviors - direct handler execution");
        sb.AppendLine("                return await handler.HandleAsync(request, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine();
        EmitBehaviorChain(sb, responseTypeName, "handler.HandleAsync(request, ct)");
        sb.AppendLine();
        sb.AppendLine("            return await next(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitSyncRequestDispatchMethod(StringBuilder sb, HandlerDescriptor handler)
    {
        var requestTypeName = handler.RequestType.ToGeneratedName();
        var responseTypeName = handler.ResponseType!.ToGeneratedName();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Optimized dispatch for {requestTypeName}.");
        sb.AppendLine("        /// Zero dictionary lookups, direct handler resolution.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public {responseTypeName} Send({requestTypeName} request)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request == null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();
        EmitBehaviorAndHandlerResolution(sb, handler, requestTypeName, responseTypeName);
        sb.AppendLine();
        sb.AppendLine("            if (behaviors.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                // No behaviors - direct handler execution");
        sb.AppendLine("                return handler.Handle(request);");
        sb.AppendLine("            }");
        sb.AppendLine();
        EmitBehaviorChain(sb, responseTypeName, "Task.FromResult(handler.Handle(request))");
        sb.AppendLine();
        sb.AppendLine("            // IPipelineBehavior is asynchronous, so a synchronous Send has to wait for the");
        sb.AppendLine("            // chain to complete. This matches IRoutya.Send, which documents that behaviors");
        sb.AppendLine("            // run asynchronously even for synchronous handlers.");
        sb.AppendLine("            return next(CancellationToken.None).GetAwaiter().GetResult();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitBehaviorAndHandlerResolution(
        StringBuilder sb,
        HandlerDescriptor handler,
        string requestTypeName,
        string responseTypeName)
    {
        var behaviorType = $"IPipelineBehavior<{requestTypeName}, {responseTypeName}>";

        // Materialized once, because the collection is otherwise enumerated twice
        sb.AppendLine($"            var resolvedBehaviors = _serviceProvider.GetServices<{behaviorType}>();");
        sb.AppendLine($"            var behaviors = resolvedBehaviors as {behaviorType}[] ?? resolvedBehaviors.ToArray();");
        sb.AppendLine($"            var handler = _serviceProvider.GetRequiredService<{handler.ConcreteType}>();");
    }

    private static void EmitBehaviorChain(StringBuilder sb, string responseTypeName, string innerCall)
    {
        sb.AppendLine($"            RequestHandlerDelegate<{responseTypeName}> next = (ct) => {innerCall};");
        sb.AppendLine();
        sb.AppendLine("            // Walked in reverse so behaviors execute in registration order");
        sb.AppendLine("            for (int i = behaviors.Length - 1; i >= 0; i--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var currentBehavior = behaviors[i];");
        sb.AppendLine("                var currentDelegate = next;");
        sb.AppendLine("                next = (ct) => currentBehavior.Handle(request, currentDelegate, ct);");
        sb.AppendLine("            }");
    }

    private static void EmitNotificationDispatchMethod(
        StringBuilder sb,
        string notificationType,
        List<HandlerDescriptor> handlers)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Optimized parallel dispatch for {notificationType}.");
        sb.AppendLine($"        /// Executes {handlers.Count} handler(s) concurrently.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public async Task PublishAsync(");
        sb.AppendLine($"            {notificationType} notification,");
        sb.AppendLine($"            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (notification == null) throw new ArgumentNullException(nameof(notification));");
        sb.AppendLine();

        // Resolve all handlers directly - caller manages scopes
        for (int i = 0; i < handlers.Count; i++)
        {
            var handler = handlers[i];
            sb.AppendLine($"            var handler{i} = _serviceProvider.GetRequiredService<{handler.ConcreteType}>();");
        }

        sb.AppendLine();

        // Execute handlers - optimized for zero allocations
        if (handlers.Count == 1)
        {
            sb.AppendLine($"            await handler0.Handle(notification, cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            // Task.WhenAll for every count above one, including two. Starting both tasks and then
            // awaiting them one after another looks equivalent, but it is not: if the first task
            // faults, the await rethrows immediately and the second task is never awaited. Its
            // exception then goes unobserved, and the caller resumes while it is still running.
            // Task.WhenAll observes every task and waits for all of them before propagating.
            sb.AppendLine("            await Task.WhenAll(");
            for (int i = 0; i < handlers.Count; i++)
            {
                var comma = i < handlers.Count - 1 ? "," : "";
                sb.AppendLine($"                handler{i}.Handle(notification, cancellationToken){comma}");
            }
            sb.AppendLine("            ).ConfigureAwait(false);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitGenericFallbackMethods(StringBuilder sb)
    {
    }

}
