using Routya.SourceGenerators.Models;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Routya.SourceGenerators.Emitters
{
    /// <summary>
    /// Emits the AddGeneratedRoutya extension method with handler registrations.
    /// </summary>
    internal static class HandlerRegistrationEmitter
    {
        public static string Generate(
            List<HandlerDescriptor> requestHandlers,
            List<HandlerDescriptor> notificationHandlers)
        {
            var sb = new StringBuilder();

            // File header
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Routya.Core.Abstractions;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            sb.AppendLine("namespace Routya.Generated");
            sb.AppendLine("{");
            
            // Generate the IGeneratedRoutya interface with only concrete methods
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Type-specific dispatcher interface generated at compile-time.");
            sb.AppendLine("    /// Use this interface for dependency injection to get concrete type-specific dispatch without generic fallbacks.");
            sb.AppendLine("    /// </summary>");
            GeneratedTypeAttributes.AppendForInterface(sb, "    ");
            sb.AppendLine("    public interface IGeneratedRoutya");
            sb.AppendLine("    {");
            
            // Add concrete Send/SendAsync methods for each request handler. Handlers whose request
            // or response type is not externally visible are skipped, because this interface is
            // public and cannot mention them. They are still registered further down.
            foreach (var handler in requestHandlers.Where(h => h.SupportsTypedDispatch))
            {
                var requestType = handler.RequestType.ToGeneratedName();
                var responseType = handler.ResponseType!.ToGeneratedName();
                
                if (handler.IsStream)
                {
                    sb.AppendLine($"        /// <summary>Streams {requestType} through its handler.</summary>");
                    sb.AppendLine($"        System.Collections.Generic.IAsyncEnumerable<{responseType}> CreateStream(");
                    sb.AppendLine($"            {requestType} request,");
                    sb.AppendLine($"            System.Threading.CancellationToken cancellationToken = default);");
                }
                else if (handler.IsAsync)
                {
                    sb.AppendLine($"        /// <summary>Dispatches {requestType} to its handler.</summary>");
                    sb.AppendLine($"        System.Threading.Tasks.Task<{responseType}> SendAsync(");
                    sb.AppendLine($"            {requestType} request,");
                    sb.AppendLine($"            System.Threading.CancellationToken cancellationToken = default);");
                }
                else
                {
                    sb.AppendLine($"        /// <summary>Dispatches {requestType} to its handler.</summary>");
                    sb.AppendLine($"        {responseType} Send({requestType} request);");
                }
                sb.AppendLine();
            }
            
            // Add concrete PublishAsync methods for each notification type
            var notificationGroups = notificationHandlers
                .Where(h => h.SupportsTypedDispatch)
                .GroupBy(h => h.RequestType.ToGeneratedName());
            foreach (var group in notificationGroups)
            {
                var notificationType = group.Key;
                sb.AppendLine($"        /// <summary>Publishes {notificationType} to all registered handlers.</summary>");
                sb.AppendLine($"        System.Threading.Tasks.Task PublishAsync(");
                sb.AppendLine($"            {notificationType} notification,");
                sb.AppendLine($"            System.Threading.CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated handler registration extensions for Routya.");
            sb.AppendLine("    /// </summary>");
            GeneratedTypeAttributes.AppendForType(sb, "    ");
            sb.AppendLine("    public static class RoutyaGeneratedExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Registers all auto-discovered handlers using source generation.");
            sb.AppendLine("        /// This provides zero-overhead, compile-time optimized dispatching.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"services\">The service collection to add handlers to.</param>");
            sb.AppendLine("        /// <param name=\"handlerLifetime\">");
            sb.AppendLine("        /// Lifetime for handlers that do not carry a RoutyaHandler attribute. Defaults to");
            sb.AppendLine("        /// Transient. Note that the runtime AddRoutya defaults to Scoped, so the two paths");
            sb.AppendLine("        /// differ unless you say otherwise here.");
            sb.AppendLine("        /// </param>");
            sb.AppendLine("        public static IServiceCollection AddGeneratedRoutya(");
            sb.AppendLine("            this IServiceCollection services,");
            sb.AppendLine("            ServiceLifetime handlerLifetime = ServiceLifetime.Transient)");
            sb.AppendLine("        {");
            
            // Request handler registrations
            if (requestHandlers.Any())
            {
                sb.AppendLine("            // Request/Response handler registrations");
                foreach (var handler in requestHandlers)
                {
                    var lifetime = GetLifetimeString(handler.Lifetime);
                    var handlerInterface = handler.IsStream
                        ? $"IStreamRequestHandler<{handler.RequestType.ToGeneratedName()}, {handler.ResponseType!.ToGeneratedName()}>"
                        : handler.IsAsync
                            ? $"IAsyncRequestHandler<{handler.RequestType.ToGeneratedName()}, {handler.ResponseType!.ToGeneratedName()}>"
                            : $"IRequestHandler<{handler.RequestType.ToGeneratedName()}, {handler.ResponseType!.ToGeneratedName()}>";
                    
                    var concrete = handler.HandlerType.ToGeneratedName();

                    if (handler.HasExplicitLifetime)
                    {
                        // A RoutyaHandler attribute fixes this handler's lifetime regardless of the
                        // argument passed to AddGeneratedRoutya.
                        sb.AppendLine($"            services.Add{lifetime}<{concrete}>();");
                        sb.AppendLine($"            services.Add{lifetime}<{handlerInterface}>(sp => sp.GetRequiredService<{concrete}>());");
                    }
                    else
                    {
                        sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({concrete}), typeof({concrete}), handlerLifetime));");
                        sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({handlerInterface}), sp => sp.GetRequiredService<{concrete}>(), handlerLifetime));");
                    }
                }
                sb.AppendLine();
            }

            // Notification handler registrations
            if (notificationHandlers.Any())
            {
                sb.AppendLine("            // Notification handler registrations");
                foreach (var handler in notificationHandlers)
                {
                    var lifetime = GetLifetimeString(handler.Lifetime);
                    var concrete = handler.HandlerType.ToGeneratedName();
                    var notificationInterface = $"INotificationHandler<{handler.RequestType.ToGeneratedName()}>";

                    if (handler.HasExplicitLifetime)
                    {
                        sb.AppendLine($"            services.Add{lifetime}<{concrete}>();");
                        sb.AppendLine($"            services.Add{lifetime}<{notificationInterface}>(sp => sp.GetRequiredService<{concrete}>());");
                    }
                    else
                    {
                        sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({concrete}), typeof({concrete}), handlerLifetime));");
                        sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({notificationInterface}), sp => sp.GetRequiredService<{concrete}>(), handlerLifetime));");
                    }
                }
                sb.AppendLine();
            }

            // Register main dispatcher
            sb.AppendLine("            // Main dispatcher registration (transient to match MediatR behavior)");
            sb.AppendLine("            services.AddTransient<GeneratedRoutya>();");
            sb.AppendLine("            services.AddTransient<IGeneratedRoutya>(sp => sp.GetRequiredService<GeneratedRoutya>());");

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetLifetimeString(ServiceLifetime lifetime)
        {
            return lifetime switch
            {
                ServiceLifetime.Singleton => "Singleton",
                ServiceLifetime.Scoped => "Scoped",
                ServiceLifetime.Transient => "Transient",
                _ => "Scoped"
            };
        }
    }
}
